### ISSUE TITLE
Sending an imgae using slash command

### ISSUE THREAD

**Issue by prashantgpt91** [jake-swanson/isituppy#1]
Can we send an **image** as well, just like you had showed how to send text to an external service.
for ex:`/upload abc.jpg`
where upload is the name of the slash command and abc.jpg is the image file to be uploaded.
If yes, can you suggest me, how to do that?

**Comment by jake-swanson** [comment]
Nope, that's not possible! The only way to upload files to Slack is by using this method, which can't really be combined with a slash command:

https://api.slack.com/methods/files.upload
